Open source pkg/config
etf1/go-config pull request #1
Opened 2020-03-16 14:07 UTC by instabledesign

2020-03-16 14:21 UTC, eko submitted a review, later dismissed

2020-03-16 14:21 UTC, eko commented on Makefile
> +	CGO_ENABLED=0 go test -count=1 -v ./...
Maybe we could add `-race` option?

2020-03-16 15:21 UTC, qneyrat submitted a review, later dismissed

2020-03-17 09:08 UTC, eko commented on README.md
> +Package e-TF1 go-config allow you to load your application config from multiple source (dotenv, env, flags...).
`allow` -> `allows`
`config` -> `configuration`
`source` -> `sources`

2020-03-17 09:08 UTC, eko commented on README.md
> +This package is build on top of [confita](https://github.com/heetch/confita)
`build` -> `built`

2020-03-17 09:08 UTC, eko commented on README.md
> +The library provider provide a DefaultConfigLoader that load from
`provide` -> `provides`

2020-03-17 09:08 UTC, eko commented on README.md
> +The library provide you a config table printer. A special tag `print:"-"` prevent config value to be printed.
`provide` -> `provides`
`prevent` -> `prevents`

2020-03-17 09:11 UTC, eko submitted a review, later dismissed

2020-03-17 12:21 UTC, pimousse1099 requested changes
I might be wrong but I think there is another **big difference** with `confita` loading sytem.

let's say we have a `.env` file :
```
MY_KEY_1="value1"
MY_KEY_2="value2"
```

and then you run your app like this:
```
go run main -my-key-1 value-from-flags
```

**With CONFITA, the config will only load the last backend values**, so it will look like this:

```
MY_KEY_1="value-from-flags"
```

whereas with this library, the config will look like this:
```
MY_KEY_1="value-from-flags"
MY_KEY_2="value2"
```

I think we must explain this in the README

2020-03-17 12:21 UTC, rmasclef commented on README.md
> +        BDDPassword: "my_fake_password",
a little tab is missing here 👍

2020-03-17 12:21 UTC, rmasclef commented on README.md
> +The library provides a DefaultConfigLoader that load from
`load` -> `loads`

2020-03-17 12:42 UTC, rmasclef commented on README.md
> +The main difference with confita is that the last loader that matches the config key will override the previous match.
maybe add something like this

```suggestion
The main differences with confita are the following:
* the final config will aggregate all the loaders results.
* the last loader that matches the config key will override the previous match.
```

2020-03-17 12:43 UTC, rmasclef commented on README.md
> +The main difference with confita is that the last loader that matches the config key will override the previous match.
but I'm still not sure that a phrase is clear enough compared to a demo or some code 👍

2020-03-17 14:04 UTC, pimousse1099 requested changes
the last commit does not cover this case : https://github.com/etf1/go-config/pull/1#pullrequestreview-375975096

yet the aditon for the empty value support is great !

2020-03-17 14:04 UTC, rmasclef commented on README.md
> + - all the backend matched value are write on given struct
```suggestion
 - all the backend matched values are written on a given struct 
```

isn't it already the case for confita ?

2020-03-17 14:04 UTC, rmasclef commented on README.md
> + - we allow to override by empty string
👍

2020-03-17 15:50 UTC, pimousse1099 approved these changes

2020-03-17 15:57 UTC, eko approved these changes

2020-03-17 15:58 UTC, qneyrat approved these changes

2020-03-17 15:59 UTC, merged